Add Conversion from Affine to PublicKey
paritytech/libsecp256k1 pull request #80
Opened 2021-09-04 06:00 UTC by Gauthamastro

PR adds core::convert From trait for PublicKey to convert an Affine to PublicKey

2021-09-13 09:29 UTC, athei approved these changes
I see no harm in merging this. But @sorpaas should know.

2021-09-13 09:33 UTC, sorpaas requested changes
An affine may be invalid when converting to a public key. I'd prefer we use `TryFrom` instead.

2021-09-14 14:53 UTC, Gauthamastro commented
@sorpaas I have implemented TryFrom, not really sure if my "if" condition is correct. Let me know

2021-09-14 15:09 UTC, sorpaas commented on src/lib.rs
> +        if value.is_infinity() | !value.is_valid_var() {
```suggestion
        if value.is_infinity() || !value.is_valid_var() {
```

2021-09-14 15:11 UTC, sorpaas commented
Please also revert those formatting change. I'm not sure it's correct since the code should have been rustfmt-ed.

2021-09-14 22:28 UTC, dvdplm requested changes
There are many white space changes here that don't seem relevant to the PR. Do you mind reverting those?

2021-09-15 03:59 UTC, Gauthamastro commented
@sorpaas @dvdplm I have fixed the formatting issue =)

2021-09-15 08:27 UTC, dvdplm approved these changes

2021-09-15 08:28 UTC, sorpaas approved these changes

2021-09-15 08:28 UTC, merged